-- ============================================================================
-- Migracion 03: Dinero con NUMERIC en vez de FLOAT (problema #6)
-- NO APLICABLE (verificado el 2026-06-10 contra la BD real).
--
-- El esquema real almacena el dinero como INTEGER en pesos chilenos:
--   Trip.suggested_price_clp  INTEGER
--   Wallet.available_balance  INTEGER
--   Wallet.escrow_balance     INTEGER
--
-- El CLP no usa decimales, por lo que INTEGER es una representacion correcta
-- y segura (sin errores de redondeo de punto flotante). No existen columnas
-- FLOAT de dinero que convertir. Las unicas columnas FLOAT son lat/lng,
-- donde float8 es apropiado.
--
-- Si en el futuro se agregan montos con decimales (otras monedas, comisiones
-- porcentuales aplicadas), usar NUMERIC(10,2) / NUMERIC(5,4).
-- ============================================================================
